module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    ID_OR_PW_NULL_VALUE: "아이디/비밀번호 값이 없습니다.",
    CREATED_USER: "회원 가입 성공",
    DELETE_USER: "회원 탈퇴 성공",
    UPDATE_USER: "회원 정보 수정 성공",

    ALREADY_USER: "이미 회원입니다.",
    NO_USER: "존재하지 않는 회원입니다.",
    MISS_MATCH_PW: "비밀번호가 맞지 않습니다.",
    LOGIN_SUCCESS: "로그인 성공",
    LOGIN_FAIL: "로그인 실패",

    PORTFOLIO_SAVE_SUCCESS: "포트폴리오 저장 성공",
    PORTFOLIO_SAVE_FAIL: "포트폴리오 저장 실패",
    PORTFOLIO_READ_FAIL: "포트폴리오 읽기 실패",
    PORTFOLIO_READ_SUCCESS : "포트폴리오 읽기 성공",
    PORTFOLIO_DETAIL_READ_FAIL: "포트폴리오 상세 읽기 실패",
    PORTFOLIO_DETAIL_REQD_SUCCESS:"포트폴리오 상세 읽기 성공",
    PORTFOLIO_DELETE_FAIL_NOT_EXIST:"포트폴리오 미존재",
    PORTFOLIO_DELETE_FAIL:"포트폴리오 삭제 실패",
    PORTFOLIO_DELETE_SUCCESS:"포트폴리오 삭제 성공",
    PORTFOLIO_DELETE_FAIL_PARAMS:"포트폴리오 번호 누락",
    PORTFOLIO_UPDATE_SUCCESS:"포트폴리오 수정 성공",
    PORTFOLIO_UPDATE_FAIL:"포트폴리오 수정 실패",

    RESUME_QUESTION_READ_FAIL : "나의 자소서 문항 불러오기 실패",
    RESUME_QUESTION_READ_SUCCESSS : "나의 자소서 문항 불러오기 성공",
    RESUME_QUESTION_HISTORY_SUCCESS:"나의 포트폴리오 불러오기 성공",
    RESUME_QUESTION_HISTORY_FAIL: "나의 포트폴리오 불러오기 실패",
    RESUME_SAVE_FAIL : "나의 자소서 저장 실패",
    RESUME_SAVE_SUCCESS : "나의 자소서 저장 성공",
    RESUME_DELETE_FAIL:"나의 자소서 삭제 실패",
    RESUME_DELETE_SUCCSS: "나의 자소서 삭제 성공", 

    INVALID_TOKEN: "잘못된 형식의 토큰입니다.",
    EMPTY_TOKEN: "토큰값이 존재하지 않습니다.",
    EXPRIED_TOKEN: "만료된 토큰입니다.",
    EMPTY_REFRESH_TOKEN: "재발급 토큰이 존재하지 않습니다.",
    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",

    NO_SELECT_AUTHORITY: "조회 권한 없음.",
    USER_SELECTED: "회원 조회 성공."
};